backend:
  name: github
  repo: cfarm/design-manual
  branch: gh-pages
  site_domain: cfarm.github.io

publish_mode: editorial_workflow

media_folder: "images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "components" # Used in routes, e.g., /admin/collections/blog
    label: "Page components" # Used in the UI
    folder: "page-components/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Component name", name: "component-name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Implementation status", name: "implementation-status", widget: "select", options: [ { label: "Proposed", value: "proposed" }, { label: "In progress", value: "in-progress" }, {label: "Beta", value: "beta" }, {label: "Released", value: "released" } ] }
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "HTML snippet", name: "html-snippet", widget: "string"}
      - {label: "Jinja2 snippet", name: "jinja2-snippet", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
